In [13]:
import requests as req
import pandas as pd
from bs4 import BeautifulSoup as bs

In [14]:
hockey_teams = ['WSH', 'PIT', 'CAR', 'NYI', 'CBJ', 'NJD', 
                'PHI', 'NYR', 'BUF', 'BOS', 'TOR', 'MTL', 
               'TBL', 'FLA', 'DET', 'OTT', 'COL', 'NSH',
               'STL', 'WPG', 'DAL', 'CHI', 'MIN', 'EDM',
               'ANA', 'VEG', 'ARI', 'CGY', 'VAN', 'SJS',
               'LAK']

base_url = "https://www.hockey-reference.com/teams/{}/{}.html"

data = req.get("https://www.hockey-reference.com/teams/CHI/2019.html")

In [22]:
stat_id = "skaters"
df_full = pd.DataFrame()

# loop through each hockey team and get data
for team in hockey_teams:
    for year in range(2010, 2021):
        url = base_url.format(team, year)
        data = req.get(url)
        soup = bs(data.text, "html.parser")

        statTable = soup.find(id = stat_id)

        # if no data, then will let us know
        if not statTable:
            print("Error: {}, {}".format(team, year))
            continue

        rows = statTable.find_all('tr') 
        listed = []
        for row in rows[:-1]:
            cols = row.find_all('td')
            cols = [x.text.strip() for x in cols]  # strip white space

            # if empty cols
            if cols:
                # appending year and team name data to row
                cols += [year, team]
                listed.append(cols)
        
        # get headers of table
        headers = []
        head_cols = statTable.find('thead').find_all('tr')[1].find_all('th')

        act_headers = []
        abr_headers = []

        for header in head_cols[1:]:
            act_header = header.get('aria-label').strip()
            abr_header = header.text.strip()
            act_headers.append(act_header)
            abr_headers.append(abr_header)
        
        # appending year and team name to the header
        act_headers += ["Year", "Team"]

        # putting the header before the actual data
        #listed = [act_headers]+listed

        df = pd.DataFrame(listed, columns = act_headers)
        df_full = df_full.append(df, ignore_index = True)

Error: WPG, 2010
Error: WPG, 2011
Error: VEG, 2010
Error: VEG, 2011
Error: VEG, 2012
Error: VEG, 2013
Error: VEG, 2014
Error: VEG, 2015
Error: VEG, 2016
Error: VEG, 2017
Error: ARI, 2010
Error: ARI, 2011
Error: ARI, 2012

In [23]:
df_full.head()

,Player,Age,Pos,Games Played,Goals,Assists,Points,Plus/Minus,Penalties in Minutes,Even Strength Goals,...,Offensive Point Shares,Defensive Point Shares,Point Shares,Blocks,Hits,Faceoff Wins,Faceoff Losses,Faceoff Percentage,Year,Team
0,Alex Ovechkin,24,LW,72,50,59,109,45,89,37,...,13.0,2.5,15.6,20,181,10,12,45.5,2010,WSH
1,Nicklas Backstrom,22,C,82,33,68,101,37,50,22,...,10.0,2.2,12.2,61,90,657,660,49.9,2010,WSH
2,Alexander Semin,25,LW,73,40,44,84,36,66,30,...,9.7,2.1,11.7,20,30,6,10,37.5,2010,WSH
3,Mike Green,24,D,75,19,57,76,39,54,9,...,8.2,4.8,13.0,105,133,0,0,,2010,WSH
4,Brooks Laich,26,C,78,25,34,59,16,34,12,...,5.2,1.3,6.4,39,92,149,178,45.6,2010,WSH

In [32]:
df_full.describe(include='all')

,Player,Age,Pos,Games Played,Goals,Assists,Points,Plus/Minus,Penalties in Minutes,Even Strength Goals,...,Offensive Point Shares,Defensive Point Shares,Point Shares,Blocks,Hits,Faceoff Wins,Faceoff Losses,Faceoff Percentage,Year,Team
count,11090,11090,11090,11090,11090,11090,11090,11090,11090,11090,...,11090,11090,11090,11090,11090,11090,11090,11090,11090.000000,11090
unique,2373,28,7,82,53,75,111,82,183,39,...,135,80,172,212,293,752,715,424,NaN,31
top,Derick Brassard,24,D,82,0,0,0,0,0,0,...,0.0,0.0,0.0,0,0,0,0,,NaN,ANA
freq,15,1016,3469,777,3500,2361,1977,1933,1937,3679,...,2185,2229,795,1485,1237,5429,5010,4844,NaN,405
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.946889,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.076558,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020.000000,NaN

In [24]:
df_full.to_csv('all.csv')